[package]
name = "imager"
version = "0.1.0"
authors = ["Cezar Lemos <cezarcbl@protonmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.6", features = ["derive"] }
image = "0.24.3"
